-- ============================================================
-- CofRe — Schema PostgreSQL (Supabase)
-- Execute no SQL Editor do Supabase em ordem
-- ============================================================

-- ── Função trigger updated_at ─────────────────────────────────
create or replace function public.set_updated_em()
returns trigger language plpgsql as $$
begin
  new.atualizado_em := current_timestamp(6);
  return new;
end;
$$;

create or replace function public.set_preferencias_definido_em()
returns trigger language plpgsql as $$
begin
  new.definido_em := current_timestamp(6);
  return new;
end;
$$;

-- ── Usuários ──────────────────────────────────────────────────
create table if not exists public.usuarios (
  id            bigint generated by default as identity primary key,
  email_hash    text not null,
  email_enc     text not null,
  nome          varchar(100) not null,
  sobrenome     varchar(100) not null,
  senha_hash    varchar(255) not null,
  kdf_salt      text not null,
  verifier_iv   text not null,
  verifier_ct   text not null,
  ativo         boolean not null default true,
  criado_em     timestamp(6) not null default current_timestamp(6),
  atualizado_em timestamp(6) not null default current_timestamp(6)
);

create unique index if not exists uq_usuarios_email_hash on public.usuarios (email_hash);

drop trigger if exists trg_usuarios_atualizado_em on public.usuarios;
create trigger trg_usuarios_atualizado_em
before update on public.usuarios
for each row execute function public.set_updated_em();

-- ── Primeiro acesso gratuito ──────────────────────────────────
create table if not exists public.acessos_gratuitos (
  email_hash           text not null primary key,
  usado_em             timestamp(6) not null default current_timestamp(6),
  primeiro_login_feito boolean not null default false
);

-- ── Planos ────────────────────────────────────────────────────
create table if not exists public.planos (
  id           smallint generated by default as identity primary key,
  slug         varchar(20) not null,
  nome         varchar(60) not null,
  descricao    varchar(255) not null,
  preco        numeric(8,2) not null,
  duracao_dias integer null,
  ativo        boolean not null default true
);

create unique index if not exists uq_planos_slug on public.planos (slug);

insert into public.planos (slug, nome, descricao, preco, duracao_dias) values
  ('por_acesso', 'Por Acesso',   'R$ 2,00 por sessão. Pague só quando usar. Ideal para uso eventual.', 2.00, null),
  ('mensal',     'Plano Mensal', 'R$ 34,90/mês. Acesso ilimitado por 30 dias. Vale a partir de 17 acessos/mês.', 34.90, 30),
  ('anual',      'Plano Anual',  'R$ 299,00/ano. R$ 24,92/mês — 29% off vs mensal. Melhor custo-benefício.', 299.00, 366)
on conflict (slug) do nothing;

-- ── Assinaturas ───────────────────────────────────────────────
create table if not exists public.assinaturas (
  id          bigint generated by default as identity primary key,
  email_hash  text not null,
  plano_id    smallint not null,
  status      text not null default 'ATIVA',
  inicio_em   timestamp(6) not null default current_timestamp(6),
  expira_em   timestamp(6) not null,
  txid_origem varchar(35) null,
  constraint ck_assinaturas_status check (status in ('ATIVA','EXPIRADA','CANCELADA')),
  constraint fk_assinaturas_plano foreign key (plano_id) references public.planos (id)
);

create index if not exists idx_assinaturas_email  on public.assinaturas (email_hash);
create index if not exists idx_assinaturas_expira on public.assinaturas (expira_em);

-- ── Categorias de credenciais ─────────────────────────────────
create table if not exists public.categorias_credenciais (
  id         integer generated by default as identity primary key,
  usuario_id bigint null,
  nome_enc   text not null,
  icone      varchar(10) not null default '📁',
  eh_sistema boolean not null default false,
  criado_em  timestamp(6) not null default current_timestamp(6)
);

create index if not exists idx_categorias_usuario on public.categorias_credenciais (usuario_id);

insert into public.categorias_credenciais (usuario_id, nome_enc, icone, eh_sistema) values
  (null, 'Banco e Cartão',      '💳', true),
  (null, 'Redes Sociais e Apps','📱', true),
  (null, 'Dispositivos',        '💻', true)
on conflict do nothing;

-- ── Credenciais ───────────────────────────────────────────────
create table if not exists public.credenciais (
  id                  bigint generated by default as identity primary key,
  usuario_id          bigint not null,
  categoria_id        integer not null,
  titulo_enc          text not null,
  login_enc           text null,
  senha_enc           text not null,
  url_ou_banco_enc    text null,
  senha_4dig_enc      text null,
  senha_6dig_enc      text null,
  numero_cartao_enc   text null,
  pin_dispositivo_enc text null,
  conta_vinculada_enc text null,
  notas_enc           text null,
  campos_extras_enc   text null,
  favorito            boolean not null default false,
  criado_em           timestamp(6) not null default current_timestamp(6),
  atualizado_em       timestamp(6) not null default current_timestamp(6),
  excluido_em         timestamp(6) null,
  constraint fk_credenciais_usuario
    foreign key (usuario_id) references public.usuarios (id) on delete cascade,
  constraint fk_credenciais_categoria
    foreign key (categoria_id) references public.categorias_credenciais (id)
);

create index if not exists idx_credenciais_usuario  on public.credenciais (usuario_id);
create index if not exists idx_credenciais_categoria on public.credenciais (categoria_id);

drop trigger if exists trg_credenciais_updated_em on public.credenciais;
create trigger trg_credenciais_updated_em
before update on public.credenciais
for each row execute function public.set_updated_em();

-- ── Cobranças Pix ─────────────────────────────────────────────
create table if not exists public.cobrancas_pix (
  id           bigint generated by default as identity primary key,
  txid         varchar(35) not null,
  email_hash   text not null,
  valor        numeric(8,2) not null,
  plano        varchar(20) not null default 'por_acesso',
  status       text not null default 'ATIVA',
  qrcode_img   text null,
  copia_cola   text null,
  token_acesso varchar(64) null,
  criado_em    timestamp(6) not null default current_timestamp(6),
  pago_em      timestamp(6) null,
  expira_em    timestamp(6) not null,
  constraint uq_cobrancas_pix_txid unique (txid),
  constraint ck_cobrancas_pix_status check (status in ('ATIVA','CONCLUIDA','EXPIRADA'))
);

create index if not exists idx_cobrancas_pix_email on public.cobrancas_pix (email_hash);
create index if not exists idx_cobrancas_pix_token on public.cobrancas_pix (token_acesso);
create index if not exists idx_cobrancas_pix_plano on public.cobrancas_pix (plano);

-- ── Sessões ───────────────────────────────────────────────────
create table if not exists public.sessoes (
  id         bigint generated by default as identity primary key,
  usuario_id bigint not null,
  token_hash varchar(128) not null,
  ip_origem  varchar(45) null,
  expira_em  timestamp(6) not null,
  criado_em  timestamp(6) not null default current_timestamp(6),
  constraint uq_sessoes_token unique (token_hash),
  constraint fk_sessoes_usuario
    foreign key (usuario_id) references public.usuarios (id) on delete cascade
);

create index if not exists idx_sessoes_usuario on public.sessoes (usuario_id);

-- ── Log de acessos ────────────────────────────────────────────
create table if not exists public.log_acessos (
  id             bigint generated by default as identity primary key,
  email_hash     text null,
  ip_origem      varchar(45) null,
  user_agent     varchar(500) null,
  sucesso        boolean not null default false,
  motivo_falha   varchar(100) null,
  plano_na_epoca varchar(20) null,
  criado_em      timestamp(6) not null default current_timestamp(6)
);

create index if not exists idx_log_acessos_email     on public.log_acessos (email_hash);
create index if not exists idx_log_acessos_criado_em on public.log_acessos (criado_em);

-- ── Histórico de sessões ──────────────────────────────────────
create table if not exists public.historico_sessoes (
  id           bigint generated by default as identity primary key,
  usuario_id   bigint not null,
  email_hash   text not null,
  ip_origem    varchar(45) null,
  user_agent   varchar(500) null,
  plano_ativo  varchar(20) null,
  iniciou_em   timestamp(6) not null default current_timestamp(6),
  encerrou_em  timestamp(6) null,
  motivo_saida varchar(30) null,
  constraint fk_historico_sessoes_usuario
    foreign key (usuario_id) references public.usuarios (id) on delete cascade
);

create index if not exists idx_historico_sessoes_usuario   on public.historico_sessoes (usuario_id);
create index if not exists idx_historico_sessoes_email     on public.historico_sessoes (email_hash);
create index if not exists idx_historico_sessoes_iniciou_em on public.historico_sessoes (iniciou_em);
create index if not exists idx_historico_sessoes_plano     on public.historico_sessoes (plano_ativo);

-- ── Preferências do usuário ───────────────────────────────────
create table if not exists public.preferencias_usuario (
  email_hash  text not null primary key,
  tema        varchar(20) not null default 'escuro',
  definido_em timestamp(6) not null default current_timestamp(6)
);

drop trigger if exists trg_preferencias_definido_em on public.preferencias_usuario;
create trigger trg_preferencias_definido_em
before update on public.preferencias_usuario
for each row execute function public.set_preferencias_definido_em();

-- ── Admin TOTP ────────────────────────────────────────────────
create table if not exists public.admin_totp (
  id         smallint generated by default as identity primary key,
  secret_b32 varchar(255) not null,
  ativo      boolean not null default true,
  criado_em  timestamp(6) not null default current_timestamp(6)
);

-- ── Admin Sessões ─────────────────────────────────────────────
create table if not exists public.admin_sessoes (
  id         bigint generated by default as identity primary key,
  token_hash varchar(128) not null,
  ip_origem  varchar(45) null,
  expira_em  timestamp(6) not null,
  criado_em  timestamp(6) not null default current_timestamp(6),
  constraint uq_admin_sessoes_token unique (token_hash)
);

-- ── RLS desabilitado (segurança implementada no Node.js) ──────
alter table public.usuarios               disable row level security;
alter table public.acessos_gratuitos      disable row level security;
alter table public.planos                 disable row level security;
alter table public.assinaturas            disable row level security;
alter table public.categorias_credenciais disable row level security;
alter table public.credenciais            disable row level security;
alter table public.cobrancas_pix          disable row level security;
alter table public.sessoes                disable row level security;
alter table public.log_acessos            disable row level security;
alter table public.historico_sessoes      disable row level security;
alter table public.preferencias_usuario   disable row level security;
alter table public.admin_totp             disable row level security;
alter table public.admin_sessoes          disable row level security;
